name: Deploy Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: 16.x


jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'
    - run: yarn
    - run: yarn lint

  test_unittests:
    needs: check
    strategy:
      matrix:
        jestgroup: ['cms/types', 'logic']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
      - run: yarn
      - run: yarn test --group=${{ matrix.jestgroup }}

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: JEST Report - ${{ matrix.jestgroup }}
          path: reports/jest-*.xml
          reporter: jest-junit

  test_func:
    needs: test_unittests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
      - run: yarn
      - run: yarn test --group=func

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: JEST Report - func
          path: reports/jest-*.xml
          reporter: jest-junit

  build:
    needs: test_func
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'
    - run: yarn
    - run: yarn build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - run: curl -X POST -d '{}' ${{ secrets.NETLIFY_DEPLOY_HOOK_URL }}
