name: Deploy Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: 16.x

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn
      - run: yarn lint

  unitTests:
    needs: check
    strategy:
      matrix:
        jestgroup: ["unit/cms/types", "unit/logic", "unit/component"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn
      - run: yarn test --group=${{ matrix.jestgroup }}

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: JEST Report - ${{ matrix.jestgroup }}
          path: reports/jest-*.xml
          reporter: jest-junit

  integrationTests:
    needs: unitTests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn
      - run: yarn test --group=integration
        env:
          STORYBLOK_GRAPHQL_ENDPOINT: "https://example.com"
          STORYBLOK_GRAPHQL_TOKEN: "NOTAREALTOKEN"
          STORYBLOK_GRAPHQL_VERSION: "draft"

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: JEST Report - integration
          path: reports/jest-*.xml
          reporter: jest-junit

  screenshotRegressionTests:
    needs: integrationTests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn
      - run: yarn chromatic:ci
        env:
          CHROMATIC_TOKEN: ${{ secrets.CHROMATIC_TOKEN }}

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Chromatic Report
          path: reports/chromatic-junit.xml
          reporter: java-junit
          fail-on-error: true

  build:
    needs: screenshotRegressionTests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn
      - run: yarn build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - run: curl -X POST -d '{}' ${{ secrets.NETLIFY_DEPLOY_HOOK_URL }}
